version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "3012:3012"
    volumes:
      - ./:/usr/src/app
    links:
      - db
    command: >
      bash -c "bash ./wait-for-it.sh db:5432 -q --
      echo DATABASE_URL=postgresql://postgres:pgpassword@db:5432/db > .env &&
      diesel setup &&
      diesel migration redo &&
      cargo run"
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: db
      PGDATA: /tmp
    image: postgres:9.6.6
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}
