version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    links:
      - db
    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:9.6.6
    ports:
      - "5432:5432"

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
