version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
#      - image: docker/compose:1.16.1

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Check Formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Unit Tests
          command: |
            cargo test
      - run:
          name: Integration Tests
          command: |
            ./integration_test.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

#  integration_tests:
#    docker:
#      - image: docker/compose:1.16.1
#
#    steps:
#      - checkout
#      - restore_cache:
#          key: project-cache
#      - run:
#          name: Integration Tests
#          command: |
#            ./integration_test.sh
#      - save_cache:
#          key: project-cache
#          paths:
#            - "~/.cargo"
#            - "./target"

#  workflows:
#    version: 2
#    run_tests:
#      jobs:
#        - build
#        - integration_tests:
#            requires:
#              - build
