version: 2

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
#      - image: docker/compose:1.16.1

    steps:
      - checkout
      - restore_cache:
          key: project-cache
     - run:
         name: Install Docker Compose
         command: |
           curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
           chmod +x ~/docker-compose
           sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Check Formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Unit Tests
          command: |
            cargo test
      - run:
          name: Integration Tests
          command: |
            ./integration_test.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

#  integration_tests:
#    docker:
#      - image: docker/compose:1.16.1
#
#    steps:
#      - checkout
#      - restore_cache:
#          key: project-cache
#      - run:
#          name: Integration Tests
#          command: |
#            ./integration_test.sh
#      - save_cache:
#          key: project-cache
#          paths:
#            - "~/.cargo"
#            - "./target"

#  workflows:
#    version: 2
#    run_tests:
#      jobs:
#        - build
#        - integration_tests:
#            requires:
#              - build
