version: 2

jobs:
  build:
    docker:
      - image: rust:slim

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt
            rustfmt --version
            cargo fmt -- --check
      - run:
          name: Test
          command: |
            rustup default nightly
            RUSTFLAGS="-C linker=x86_64-unknown-linux-gnu" cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"