[package]
name = "integration"
version = "0.1.0"
authors = ["Sean Smith <sean.smith@tenx.tech>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
serde = "1.0.86"
serde_json = "1.0"
serde_derive = "1.0.86"